### ISSUE TITLE
Note that we don't update old tags

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/cimg-overview#9]
It should be clear in this repo, as well as the readmes for each image, that we don't go back to old Docker tags to update them for never software releases. That would go against the stability/determinism ethos that next-gen images have.

**Comment by wKovacs64** [comment]
I assume that same ethos is why there is no `lts` tag?

**Comment by JalexChen** [comment]
Hi @wKovacs64, there are images that do utilize an LTS tag as an alias if it's specified. For example, we update the Node image LTS version based off what is on the officially supported Node website.

In the case where you'd like to utilize a specific tag, an orb would be useful to pin the version you'd like to use while utilizing newer versions of packages and dependencies.
